/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
MyFirstVstAudioProcessor::MyFirstVstAudioProcessor()
{
}

MyFirstVstAudioProcessor::~MyFirstVstAudioProcessor()
{
}

//==============================================================================
const String MyFirstVstAudioProcessor::getName() const
{
    return JucePlugin_Name;
}

int MyFirstVstAudioProcessor::getNumParameters()
{
    return 0;
}

float MyFirstVstAudioProcessor::getParameter (int index)
{
    return 0.0f;
}

void MyFirstVstAudioProcessor::setParameter (int index, float newValue)
{
}

const String MyFirstVstAudioProcessor::getParameterName (int index)
{
    return String();
}

const String MyFirstVstAudioProcessor::getParameterText (int index)
{
    return String();
}

const String MyFirstVstAudioProcessor::getInputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

const String MyFirstVstAudioProcessor::getOutputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

bool MyFirstVstAudioProcessor::isInputChannelStereoPair (int index) const
{
    return true;
}

bool MyFirstVstAudioProcessor::isOutputChannelStereoPair (int index) const
{
    return true;
}

bool MyFirstVstAudioProcessor::acceptsMidi() const
{
   #if JucePlugin_WantsMidiInput
    return true;
   #else
    return false;
   #endif
}

bool MyFirstVstAudioProcessor::producesMidi() const
{
   #if JucePlugin_ProducesMidiOutput
    return true;
   #else
    return false;
   #endif
}

bool MyFirstVstAudioProcessor::silenceInProducesSilenceOut() const
{
    return false;
}

double MyFirstVstAudioProcessor::getTailLengthSeconds() const
{
    return 0.0;
}

int MyFirstVstAudioProcessor::getNumPrograms()
{
    return 1;   // NB: some hosts don't cope very well if you tell them there are 0 programs,
                // so this should be at least 1, even if you're not really implementing programs.
}

int MyFirstVstAudioProcessor::getCurrentProgram()
{
    return 0;
}

void MyFirstVstAudioProcessor::setCurrentProgram (int index)
{
}

const String MyFirstVstAudioProcessor::getProgramName (int index)
{
    return String();
}

void MyFirstVstAudioProcessor::changeProgramName (int index, const String& newName)
{
}

//==============================================================================
void MyFirstVstAudioProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
    // Use this method as the place to do any pre-playback
    // initialisation that you need..
}

void MyFirstVstAudioProcessor::releaseResources()
{
    // When playback stops, you can use this as an opportunity to free up any
    // spare memory, etc.
}

void MyFirstVstAudioProcessor::processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages)
{
    buffer.clear();
    
    MidiBuffer processedMidi;
    int time;
    
    MidiMessage m;
    
    for (MidiBuffer::Iterator i (midiMessages); i.getNextEvent(m, time);) {
        if (m.isNoteOn()) {
            uint8 newVel = (uint8)noteOnVel;
            m = MidiMessage::noteOn(m.getChannel(), m.getNoteNumber(), newVel);
        }
        else if (m.isNoteOff()){}
        else if (m.isAftertouch()){}
        else if (m.isPitchWheel()){}
        
        processedMidi.addEvent(m, time);
    }
    
    midiMessages.swapWith(processedMidi);
}

//==============================================================================
bool MyFirstVstAudioProcessor::hasEditor() const
{
    return true; // (change this to false if you choose to not supply an editor)
}

AudioProcessorEditor* MyFirstVstAudioProcessor::createEditor()
{
    return new MyFirstVstAudioProcessorEditor (*this);
}

//==============================================================================
void MyFirstVstAudioProcessor::getStateInformation (MemoryBlock& destData)
{
    // You should use this method to store your parameters in the memory block.
    // You could do that either as raw data, or use the XML or ValueTree classes
    // as intermediaries to make it easy to save and load complex data.
}

void MyFirstVstAudioProcessor::setStateInformation (const void* data, int sizeInBytes)
{
    // You should use this method to restore your parameters from this memory block,
    // whose contents will have been created by the getStateInformation() call.
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new MyFirstVstAudioProcessor();
}





































